// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZM_aCCuZi5GJerc7cEc0IHuzKsn-7fe0',
    appId: '1:99005791879:web:8b9a6bbd627e86463ac222',
    messagingSenderId: '99005791879',
    projectId: 'sorteo-ipv',
    authDomain: 'sorteo-ipv.firebaseapp.com',
    storageBucket: 'sorteo-ipv.firebasestorage.app',
    measurementId: 'G-T35BCF5BR3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZM_aCCuZi5GJerc7cEc0IHuzKsn-7fe0',
    appId: '1:99005791879:web:d95a38f5cb7418733ac222',
    messagingSenderId: '99005791879',
    projectId: 'sorteo-ipv',
    authDomain: 'sorteo-ipv.firebaseapp.com',
    storageBucket: 'sorteo-ipv.firebasestorage.app',
    measurementId: 'G-GL8ZHXET9X',
  );
}
